alloc_var_R8P_4D – PENF
alloc_var_R8P_4D Subroutine
27 statements
Source File
private subroutine alloc_var_R8P_4D(var, ulb, file_unit, msg, verbose)
Allocate CPU variable with memory checking (kind R8P, rank 4).
 use penf
 real(R8P), allocatable :: a(:,:,:,:)
 integer(I4P)           :: ulb(2,4)=reshape([1,1, &
                                             1,2, &
                                             1,3, &
                                             1,4],&
                                            [2,4])
 open(unit=666, file='doctest-mem.log')
 call allocate_variable(a, ulb, file_unit=666, verbose=.true.)
 close(666, status='delete')
 print*, allocated(a)
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(inout), allocatable :: var(:,:,:,:)
Varibale to be allocate on CPU.
integer(kind=I4P), intent(in) :: ulb(2,4)
Upper/lower bounds of variable.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
Calls
Called by
Source Code
   subroutine alloc_var_R8P_4D(var, ulb, file_unit, msg, verbose)
   !< Allocate CPU variable with memory checking (kind R8P, rank 4).
   !<
   !<```fortran
   !< use penf
   !< real(R8P), allocatable :: a(:,:,:,:)
   !< integer(I4P)           :: ulb(2,4)=reshape([1,1, &
   !<                                             1,2, &
   !<                                             1,3, &
   !<                                             1,4],&
   !<                                            [2,4])
   !< open(unit=666, file='doctest-mem.log')
   !< call allocate_variable(a, ulb, file_unit=666, verbose=.true.)
   !< close(666, status='delete')
   !< print*, allocated(a)
   !<```
   !=> T <<<
   real(R8P), allocatable, intent(inout)        :: var(:,:,:,:)        !< Varibale to be allocate on CPU.
   integer(I4P),           intent(in)           :: ulb(2,4)            !< Upper/lower bounds of variable.
   integer(I4P),           intent(in), optional :: file_unit           !< File unit for verbose output.
   character(*),           intent(in), optional :: msg                 !< Message to be printed in verbose mode.
   logical,                intent(in), optional :: verbose             !< Flag to activate verbose mode.
   integer(I4P)                                 :: file_unit_          !< File unit for verbose output, local var.
   character(:), allocatable                    :: msg_                !< Message to be printed in verbose mode, local var.
   logical                                      :: verbose_            !< Flag to activate verbose mode, local var.
   integer(I8P)                                 :: mem_free, mem_total !< CPU memory.
   file_unit_ = stdout  ; if (present(file_unit)) file_unit_ = file_unit
   msg_       = ''      ; if (present(msg    ))   msg_       = msg
   verbose_   = .false. ; if (present(verbose))   verbose_   = verbose
   if (allocated(var)) deallocate(var)
   if (verbose_) then
      call get_memory_info(mem_total, mem_free)
      write(file_unit_,'(A)') msg_//'free/total memory BEFORE allocate:'//trim(str([mem_free,mem_total]))//'[bytes]'
   endif
   allocate(var(ulb(1,1):ulb(2,1), ulb(1,2):ulb(2,2), ulb(1,3):ulb(2,3), ulb(1,4):ulb(2,4)))
   if (verbose_) then
      call get_memory_info(mem_total, mem_free)
      write(file_unit_,'(A)') msg_//'free/total memory AFTER  allocate:'//trim(str([mem_free,mem_total]))//'[bytes]'
   endif
   endsubroutine alloc_var_R8P_4D
Call graph
alloc_var_r8p_4d calls str, get_memory_info
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
get_memory_info calls cton
cton calls ctoi_i1p, ctoi_i2p, ctoi_i4p, ctoi_i8p, ctor_r4p, ctor_r8p
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
allocate_variable calls alloc_var_r8p_4d
assign_allocatable_i1p_1d calls allocate_variable
assign_allocatable_i1p_2d calls allocate_variable
assign_allocatable_i1p_3d calls allocate_variable
assign_allocatable_i1p_4d calls allocate_variable
assign_allocatable_i1p_5d calls allocate_variable
assign_allocatable_i1p_6d calls allocate_variable
assign_allocatable_i1p_7d calls allocate_variable
assign_allocatable_i2p_1d calls allocate_variable
assign_allocatable_i2p_2d calls allocate_variable
assign_allocatable_i2p_3d calls allocate_variable
assign_allocatable_i2p_4d calls allocate_variable
assign_allocatable_i2p_5d calls allocate_variable
assign_allocatable_i2p_6d calls allocate_variable
assign_allocatable_i2p_7d calls allocate_variable
assign_allocatable_i4p_1d calls allocate_variable
assign_allocatable_i4p_2d calls allocate_variable
assign_allocatable_i4p_3d calls allocate_variable
assign_allocatable_i4p_4d calls allocate_variable
assign_allocatable_i4p_5d calls allocate_variable
assign_allocatable_i4p_6d calls allocate_variable
assign_allocatable_i4p_7d calls allocate_variable
assign_allocatable_i8p_1d calls allocate_variable
assign_allocatable_i8p_2d calls allocate_variable
assign_allocatable_i8p_3d calls allocate_variable
assign_allocatable_i8p_4d calls allocate_variable
assign_allocatable_i8p_5d calls allocate_variable
assign_allocatable_i8p_6d calls allocate_variable
assign_allocatable_i8p_7d calls allocate_variable
assign_allocatable_r16p_1d calls allocate_variable
assign_allocatable_r16p_2d calls allocate_variable
assign_allocatable_r16p_3d calls allocate_variable
assign_allocatable_r16p_4d calls allocate_variable
assign_allocatable_r16p_5d calls allocate_variable
assign_allocatable_r16p_6d calls allocate_variable
assign_allocatable_r16p_7d calls allocate_variable
assign_allocatable_r4p_1d calls allocate_variable
assign_allocatable_r4p_2d calls allocate_variable
assign_allocatable_r4p_3d calls allocate_variable
assign_allocatable_r4p_4d calls allocate_variable
assign_allocatable_r4p_5d calls allocate_variable
assign_allocatable_r4p_6d calls allocate_variable
assign_allocatable_r4p_7d calls allocate_variable
assign_allocatable_r8p_1d calls allocate_variable
assign_allocatable_r8p_2d calls allocate_variable
assign_allocatable_r8p_3d calls allocate_variable
assign_allocatable_r8p_4d calls allocate_variable
assign_allocatable_r8p_5d calls allocate_variable
assign_allocatable_r8p_6d calls allocate_variable
assign_allocatable_r8p_7d calls allocate_variable
volatile_doctest calls allocate_variable, assign_allocatable
assign_allocatable calls assign_allocatable_i1p_1d, assign_allocatable_i1p_2d, assign_allocatable_i1p_3d, assign_allocatable_i1p_4d, assign_allocatable_i1p_5d, assign_allocatable_i1p_6d, assign_allocatable_i1p_7d, assign_allocatable_i2p_1d, assign_allocatable_i2p_2d, assign_allocatable_i2p_3d, assign_allocatable_i2p_4d, assign_allocatable_i2p_5d, assign_allocatable_i2p_6d, assign_allocatable_i2p_7d, assign_allocatable_i4p_1d, assign_allocatable_i4p_2d, assign_allocatable_i4p_3d, assign_allocatable_i4p_4d, assign_allocatable_i4p_5d, assign_allocatable_i4p_6d, assign_allocatable_i4p_7d, assign_allocatable_i8p_1d, assign_allocatable_i8p_2d, assign_allocatable_i8p_3d, assign_allocatable_i8p_4d, assign_allocatable_i8p_5d, assign_allocatable_i8p_6d, assign_allocatable_i8p_7d, assign_allocatable_r4p_1d, assign_allocatable_r4p_2d, assign_allocatable_r4p_3d, assign_allocatable_r4p_4d, assign_allocatable_r4p_5d, assign_allocatable_r4p_6d, assign_allocatable_r4p_7d, assign_allocatable_r8p_1d, assign_allocatable_r8p_2d, assign_allocatable_r8p_3d, assign_allocatable_r8p_4d, assign_allocatable_r8p_5d, assign_allocatable_r8p_6d, assign_allocatable_r8p_7d