assign_allocatable_I4P_7D – PENF
assign_allocatable_I4P_7D Subroutine
13 statements
Source File
private subroutine assign_allocatable_I4P_7D(lhs, rhs, msg, verbose)
Assign CPU variable with memory checking (kind I4P, rank 7). Variable is returned not allocated if right hand side is not allocated.
 use penf
 integer(I4P), allocatable :: a(:,:,:,:,:,:,:), b(:,:,:,:,:,:,:)
 allocate(b(1:1,1:2,1:3,1:4,1:5,1:6,1:7))
 call assign_allocatable(a, b)
 print*, allocated(a)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(inout), allocatable :: lhs(:,:,:,:,:,:,:)
Left hand side of assignement.
integer(kind=I4P), intent(in), allocatable :: rhs(:,:,:,:,:,:,:)
Right hand side of assignement.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
Calls
Called by
Source Code
   subroutine assign_allocatable_I4P_7D(lhs, rhs, msg, verbose)
   !< Assign CPU variable with memory checking (kind I4P, rank 7).
   !< Variable is returned not allocated if right hand side is not allocated.
   !<
   !<```fortran
   !< use penf
   !< integer(I4P), allocatable :: a(:,:,:,:,:,:,:), b(:,:,:,:,:,:,:)
   !< allocate(b(1:1,1:2,1:3,1:4,1:5,1:6,1:7))
   !< call assign_allocatable(a, b)
   !< print*, allocated(a)
   !<```
   !=> T <<<
   integer(I4P), allocatable, intent(inout)        :: lhs(:,:,:,:,:,:,:) !< Left hand side of assignement.
   integer(I4P), allocatable, intent(in)           :: rhs(:,:,:,:,:,:,:) !< Right hand side of assignement.
   character(*),              intent(in), optional :: msg                !< Message to be printed in verbose mode.
   logical,                   intent(in), optional :: verbose            !< Flag to activate verbose mode.
   if (allocated(lhs)) deallocate(lhs)
   if (allocated(rhs)) then
      if (size(rhs,dim=1)*size(rhs,dim=2)*size(rhs,dim=3)*size(rhs,dim=4)*size(rhs,dim=5)*size(rhs,dim=6)*size(rhs,dim=7)>0) then
         call allocate_variable(var=lhs,                                                  &
                                ulb=reshape([lbound(rhs,dim=1),ubound(rhs,dim=1),         &
                                             lbound(rhs,dim=2),ubound(rhs,dim=2),         &
                                             lbound(rhs,dim=3),ubound(rhs,dim=3),         &
                                             lbound(rhs,dim=4),ubound(rhs,dim=4),         &
                                             lbound(rhs,dim=5),ubound(rhs,dim=5),         &
                                             lbound(rhs,dim=6),ubound(rhs,dim=6),         &
                                             lbound(rhs,dim=7),ubound(rhs,dim=7)],[2,7]), &
                                msg=msg, verbose=verbose)
         lhs = rhs
      endif
   endif
   endsubroutine assign_allocatable_I4P_7D
Call graph
assign_allocatable_i4p_7d calls allocate_variable
allocate_variable calls alloc_var_i1p_1d, alloc_var_i1p_2d, alloc_var_i1p_3d, alloc_var_i1p_4d, alloc_var_i1p_5d, alloc_var_i1p_6d, alloc_var_i1p_7d, alloc_var_i2p_1d, alloc_var_i2p_2d, alloc_var_i2p_3d, alloc_var_i2p_4d, alloc_var_i2p_5d, alloc_var_i2p_6d, alloc_var_i2p_7d, alloc_var_i4p_1d, alloc_var_i4p_2d, alloc_var_i4p_3d, alloc_var_i4p_4d, alloc_var_i4p_5d, alloc_var_i4p_6d, alloc_var_i4p_7d, alloc_var_i8p_1d, alloc_var_i8p_2d, alloc_var_i8p_3d, alloc_var_i8p_4d, alloc_var_i8p_5d, alloc_var_i8p_6d, alloc_var_i8p_7d, alloc_var_r4p_1d, alloc_var_r4p_2d, alloc_var_r4p_3d, alloc_var_r4p_4d, alloc_var_r4p_5d, alloc_var_r4p_6d, alloc_var_r4p_7d, alloc_var_r8p_1d, alloc_var_r8p_2d, alloc_var_r8p_3d, alloc_var_r8p_4d, alloc_var_r8p_5d, alloc_var_r8p_6d, alloc_var_r8p_7d
alloc_var_i1p_1d calls str, get_memory_info
alloc_var_i1p_2d calls str, get_memory_info
alloc_var_i1p_3d calls str, get_memory_info
alloc_var_i1p_4d calls str, get_memory_info
alloc_var_i1p_5d calls str, get_memory_info
alloc_var_i1p_6d calls str, get_memory_info
alloc_var_i1p_7d calls str, get_memory_info
alloc_var_i2p_1d calls str, get_memory_info
alloc_var_i2p_2d calls str, get_memory_info
alloc_var_i2p_3d calls str, get_memory_info
alloc_var_i2p_4d calls str, get_memory_info
alloc_var_i2p_5d calls str, get_memory_info
alloc_var_i2p_6d calls str, get_memory_info
alloc_var_i2p_7d calls str, get_memory_info
alloc_var_i4p_1d calls str, get_memory_info
alloc_var_i4p_2d calls str, get_memory_info
alloc_var_i4p_3d calls str, get_memory_info
alloc_var_i4p_4d calls str, get_memory_info
alloc_var_i4p_5d calls str, get_memory_info
alloc_var_i4p_6d calls str, get_memory_info
alloc_var_i4p_7d calls str, get_memory_info
alloc_var_i8p_1d calls str, get_memory_info
alloc_var_i8p_2d calls str, get_memory_info
alloc_var_i8p_3d calls str, get_memory_info
alloc_var_i8p_4d calls str, get_memory_info
alloc_var_i8p_5d calls str, get_memory_info
alloc_var_i8p_6d calls str, get_memory_info
alloc_var_i8p_7d calls str, get_memory_info
alloc_var_r4p_1d calls str, get_memory_info
alloc_var_r4p_2d calls str, get_memory_info
alloc_var_r4p_3d calls str, get_memory_info
alloc_var_r4p_4d calls str, get_memory_info
alloc_var_r4p_5d calls str, get_memory_info
alloc_var_r4p_6d calls str, get_memory_info
alloc_var_r4p_7d calls str, get_memory_info
alloc_var_r8p_1d calls str, get_memory_info
alloc_var_r8p_2d calls str, get_memory_info
alloc_var_r8p_3d calls str, get_memory_info
alloc_var_r8p_4d calls str, get_memory_info
alloc_var_r8p_5d calls str, get_memory_info
alloc_var_r8p_6d calls str, get_memory_info
alloc_var_r8p_7d calls str, get_memory_info
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
get_memory_info calls cton
cton calls ctoi_i1p, ctoi_i2p, ctoi_i4p, ctoi_i8p, ctor_r4p, ctor_r8p
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
assign_allocatable calls assign_allocatable_i4p_7d
volatile_doctest calls assign_allocatable