byte_size_R8P – PENF
byte_size_R8P Function
5 statements
Source File
private elemental function byte_size_R8P(i) result(bytes)
Compute the number of bytes of a real variable.
 use penf
 print FI1P, byte_size(1._R8P)
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: i
Real variable whose number of bytes must be computed.
Return Value integer(kind=I1P)
Number of bytes of r.
Called by
Source Code
   elemental function byte_size_R8P(i) result(bytes)
   !< Compute the number of bytes of a real variable.
   !<
   !<```fortran
   !< use penf
   !< print FI1P, byte_size(1._R8P)
   !<```
   !=> 8 <<<
   real(R8P), intent(in) :: i     !< Real variable whose number of bytes must be computed.
   integer(I1P)          :: bytes !< Number of bytes of r.
   bytes = bit_size(i) / 8_I1P
   endfunction byte_size_R8P
Call graph
byte_size calls byte_size_r8p
volatile_doctest calls byte_size