byte_size_I1P – PENF
byte_size_I1P Function
5 statements
Source File
private elemental function byte_size_I1P(i) result(bytes)
Compute the number of bytes of an integer variable.
 use penf
 print FI1P, byte_size(1_I1P)
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: i
Integer variable whose number of bytes must be computed.
Return Value integer(kind=I1P)
Number of bytes of i.
Called by
Contents
Source Code
byte_size_I1P
Source Code
   elemental function byte_size_I1P(i) result(bytes)
   !< Compute the number of bytes of an integer variable.
   !<
   !<```fortran
   !< use penf
   !< print FI1P, byte_size(1_I1P)
   !<```
   !=> 1 <<<
   integer(I1P), intent(in) :: i     !< Integer variable whose number of bytes must be computed.
   integer(I1P)             :: bytes !< Number of bytes of i.
   bytes = bit_size(i) / 8_I1P
   endfunction byte_size_I1P
Call graph
byte_size calls byte_size_i1p
volatile_doctest calls byte_size