check_endian – PENF
check_endian Subroutine
14 statements
Source File
public subroutine check_endian()
Check the type of bit ordering (big or little endian) of the running architecture.
Note
The result is stored into the endian global variable.
Arguments
None
Called By
Source Code
check_endian
Source Code
  subroutine check_endian()
  !< Check the type of bit ordering (big or little endian) of the running architecture.
  !<
  !> @note The result is stored into the *endian* global variable.
  if (is_little_endian()) then
    endian = endianL
  else
    endian = endianB
  endif
  contains
    pure function is_little_endian() result(is_little)
    !< Check if the type of the bit ordering of the running architecture is little endian.
    logical      :: is_little !< Logical output: true is the running architecture uses little endian ordering, false otherwise.
    integer(I1P) :: int1(1:4) !< One byte integer array for casting 4 bytes integer.
    int1 = transfer(1_I4P, int1)
    is_little = (int1(1)==1_I1P)
    endfunction is_little_endian
  endsubroutine check_endian
All Procedures
bctoi_I1P bctoi_I2P bctoi_I4P bctoi_I8P bcton bctor_R16P bctor_R4P bctor_R8P bit_size bit_size bit_size_chr bit_size_R16P bit_size_R4P bit_size_R8P bstr bstr_I1P bstr_I2P bstr_I4P bstr_I8P bstr_R16P bstr_R4P bstr_R8P byte_size byte_size_chr byte_size_I1P byte_size_I2P byte_size_I4P byte_size_I8P byte_size_R16P byte_size_R4P byte_size_R8P check_endian compact_real_string ctoi_I1P ctoi_I2P ctoi_I4P ctoi_I8P cton ctor_R16P ctor_R4P ctor_R8P digit digit_I1 digit_I2 digit_I4 digit_I8 penf_init penf_print str str_a_I1P str_a_I2P str_a_I4P str_a_I8P str_a_R16P str_a_R4P str_a_R8P str_ascii str_ascii_ascii str_ascii_default str_ascii_ucs4 str_bol str_I1P str_I2P str_I4P str_I8P str_R16P str_R4P str_R8P str_ucs4 str_ucs4_ascii str_ucs4_default str_ucs4_ucs4 strf_I1P strf_I2P strf_I4P strf_I8P strf_R16P strf_R4P strf_R8P strz strz_I1P strz_I2P strz_I4P strz_I8P
Call graph
penf_init calls check_endian
penf_test_all calls penf_init
penf_test_compact_real calls penf_init