str_a_R8P – PENF
str_a_R8P Function
20 statements
Source File
private pure function str_a_R8P(n, no_sign, separator, delimiters, compact) result(str)
Convert real array to string.
 use penf
 print "(A)", str(n=[1._R8P, -2._R8P])
 use penf
 print "(A)", str(n=[1._R8P, 2._R8P], no_sign=.true.)
 use penf
 print "(A)", str(n=[1._R8P, -2._R8P], separator='|')
 use penf
 print "(A)", str(n=[1._R8P, -2._R8P], delimiters=['(', ')'])
 use penf
 print "(A)", str(n=[1._R8P, -2._R8P], compact=.true.)
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: n(:)
Real array to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
character(len=1), intent(in), optional :: separator
Eventual separator of array values.
character(len=*), intent(in), optional :: delimiters(1:2)
Eventual delimiters of array values.
logical, intent(in), optional :: compact
Flag for compacting string encoding.
Return Value character(len=:), allocatable
Returned string containing input number.
Calls
Called by
Source Code
   pure function str_a_R8P(n, no_sign, separator, delimiters, compact) result(str)
   !< Convert real array to string.
   !<
   !<```fortran
   !< use penf
   !< print "(A)", str(n=[1._R8P, -2._R8P])
   !<```
   !=> +0.100000000000000E+001,-0.200000000000000E+001 <<<
   !<
   !<```fortran
   !< use penf
   !< print "(A)", str(n=[1._R8P, 2._R8P], no_sign=.true.)
   !<```
   !=> 0.100000000000000E+001,0.200000000000000E+001 <<<
   !<
   !<```fortran
   !< use penf
   !< print "(A)", str(n=[1._R8P, -2._R8P], separator='|')
   !<```
   !=> +0.100000000000000E+001|-0.200000000000000E+001 <<<
   !<
   !<```fortran
   !< use penf
   !< print "(A)", str(n=[1._R8P, -2._R8P], delimiters=['(', ')'])
   !<```
   !=> (+0.100000000000000E+001,-0.200000000000000E+001) <<<
   !<
   !<```fortran
   !< use penf
   !< print "(A)", str(n=[1._R8P, -2._R8P], compact=.true.)
   !<```
   !=> +0.1E+1,-0.2E+1 <<<
   real(R8P),    intent(in)           :: n(:)            !< Real array to be converted.
   logical,      intent(in), optional :: no_sign         !< Flag for leaving out the sign.
   character(1), intent(in), optional :: separator       !< Eventual separator of array values.
   character(*), intent(in), optional :: delimiters(1:2) !< Eventual delimiters of array values.
   logical,      intent(in), optional :: compact         !< Flag for *compacting* string encoding.
   character(len=:), allocatable      :: str             !< Returned string containing input number.
   character(DR8P)                    :: strn            !< String containing of element of input array number.
   character(len=1)                   :: sep             !< Array values separator
   integer                            :: i               !< Counter.
   str = ''
   sep = ','
   if(present(separator)) sep = separator
   do i=1,size(n)
     strn = str_R8P(no_sign=no_sign, compact=compact, n=n(i))
     str = str//sep//trim(strn)
   enddo
   str = trim(str(2:))
   if (present(delimiters)) str = delimiters(1)//str//delimiters(2)
   endfunction str_a_R8P
Call graph
str_a_r8p calls str_r8p
str_r8p calls compact_real_string
str calls str_a_r8p
alloc_var_i1p_1d calls str
alloc_var_i1p_2d calls str
alloc_var_i1p_3d calls str
alloc_var_i1p_4d calls str
alloc_var_i1p_5d calls str
alloc_var_i1p_6d calls str
alloc_var_i1p_7d calls str
alloc_var_i2p_1d calls str
alloc_var_i2p_2d calls str
alloc_var_i2p_3d calls str
alloc_var_i2p_4d calls str
alloc_var_i2p_5d calls str
alloc_var_i2p_6d calls str
alloc_var_i2p_7d calls str
alloc_var_i4p_1d calls str
alloc_var_i4p_2d calls str
alloc_var_i4p_3d calls str
alloc_var_i4p_4d calls str
alloc_var_i4p_5d calls str
alloc_var_i4p_6d calls str
alloc_var_i4p_7d calls str
alloc_var_i8p_1d calls str
alloc_var_i8p_2d calls str
alloc_var_i8p_3d calls str
alloc_var_i8p_4d calls str
alloc_var_i8p_5d calls str
alloc_var_i8p_6d calls str
alloc_var_i8p_7d calls str
alloc_var_r16p_1d calls str
alloc_var_r16p_2d calls str
alloc_var_r16p_3d calls str
alloc_var_r16p_4d calls str
alloc_var_r16p_5d calls str
alloc_var_r16p_6d calls str
alloc_var_r16p_7d calls str
alloc_var_r4p_1d calls str
alloc_var_r4p_2d calls str
alloc_var_r4p_3d calls str
alloc_var_r4p_4d calls str
alloc_var_r4p_5d calls str
alloc_var_r4p_6d calls str
alloc_var_r4p_7d calls str
alloc_var_r8p_1d calls str
alloc_var_r8p_2d calls str
alloc_var_r8p_3d calls str
alloc_var_r8p_4d calls str
alloc_var_r8p_5d calls str
alloc_var_r8p_6d calls str
alloc_var_r8p_7d calls str
bctoi_i1p calls str
bctoi_i2p calls str
bctoi_i4p calls str
bctoi_i8p calls str
volatile_doctest calls str, allocate_variable, bcton, assign_allocatable
allocate_variable calls alloc_var_i1p_1d, alloc_var_i1p_2d, alloc_var_i1p_3d, alloc_var_i1p_4d, alloc_var_i1p_5d, alloc_var_i1p_6d, alloc_var_i1p_7d, alloc_var_i2p_1d, alloc_var_i2p_2d, alloc_var_i2p_3d, alloc_var_i2p_4d, alloc_var_i2p_5d, alloc_var_i2p_6d, alloc_var_i2p_7d, alloc_var_i4p_1d, alloc_var_i4p_2d, alloc_var_i4p_3d, alloc_var_i4p_4d, alloc_var_i4p_5d, alloc_var_i4p_6d, alloc_var_i4p_7d, alloc_var_i8p_1d, alloc_var_i8p_2d, alloc_var_i8p_3d, alloc_var_i8p_4d, alloc_var_i8p_5d, alloc_var_i8p_6d, alloc_var_i8p_7d, alloc_var_r4p_1d, alloc_var_r4p_2d, alloc_var_r4p_3d, alloc_var_r4p_4d, alloc_var_r4p_5d, alloc_var_r4p_6d, alloc_var_r4p_7d, alloc_var_r8p_1d, alloc_var_r8p_2d, alloc_var_r8p_3d, alloc_var_r8p_4d, alloc_var_r8p_5d, alloc_var_r8p_6d, alloc_var_r8p_7d
bcton calls bctoi_i1p, bctoi_i2p, bctoi_i4p, bctoi_i8p
assign_allocatable_i1p_1d calls allocate_variable
assign_allocatable_i1p_2d calls allocate_variable
assign_allocatable_i1p_3d calls allocate_variable
assign_allocatable_i1p_4d calls allocate_variable
assign_allocatable_i1p_5d calls allocate_variable
assign_allocatable_i1p_6d calls allocate_variable
assign_allocatable_i1p_7d calls allocate_variable
assign_allocatable_i2p_1d calls allocate_variable
assign_allocatable_i2p_2d calls allocate_variable
assign_allocatable_i2p_3d calls allocate_variable
assign_allocatable_i2p_4d calls allocate_variable
assign_allocatable_i2p_5d calls allocate_variable
assign_allocatable_i2p_6d calls allocate_variable
assign_allocatable_i2p_7d calls allocate_variable
assign_allocatable_i4p_1d calls allocate_variable
assign_allocatable_i4p_2d calls allocate_variable
assign_allocatable_i4p_3d calls allocate_variable
assign_allocatable_i4p_4d calls allocate_variable
assign_allocatable_i4p_5d calls allocate_variable
assign_allocatable_i4p_6d calls allocate_variable
assign_allocatable_i4p_7d calls allocate_variable
assign_allocatable_i8p_1d calls allocate_variable
assign_allocatable_i8p_2d calls allocate_variable
assign_allocatable_i8p_3d calls allocate_variable
assign_allocatable_i8p_4d calls allocate_variable
assign_allocatable_i8p_5d calls allocate_variable
assign_allocatable_i8p_6d calls allocate_variable
assign_allocatable_i8p_7d calls allocate_variable
assign_allocatable_r16p_1d calls allocate_variable
assign_allocatable_r16p_2d calls allocate_variable
assign_allocatable_r16p_3d calls allocate_variable
assign_allocatable_r16p_4d calls allocate_variable
assign_allocatable_r16p_5d calls allocate_variable
assign_allocatable_r16p_6d calls allocate_variable
assign_allocatable_r16p_7d calls allocate_variable
assign_allocatable_r4p_1d calls allocate_variable
assign_allocatable_r4p_2d calls allocate_variable
assign_allocatable_r4p_3d calls allocate_variable
assign_allocatable_r4p_4d calls allocate_variable
assign_allocatable_r4p_5d calls allocate_variable
assign_allocatable_r4p_6d calls allocate_variable
assign_allocatable_r4p_7d calls allocate_variable
assign_allocatable_r8p_1d calls allocate_variable
assign_allocatable_r8p_2d calls allocate_variable
assign_allocatable_r8p_3d calls allocate_variable
assign_allocatable_r8p_4d calls allocate_variable
assign_allocatable_r8p_5d calls allocate_variable
assign_allocatable_r8p_6d calls allocate_variable
assign_allocatable_r8p_7d calls allocate_variable
assign_allocatable calls assign_allocatable_i1p_1d, assign_allocatable_i1p_2d, assign_allocatable_i1p_3d, assign_allocatable_i1p_4d, assign_allocatable_i1p_5d, assign_allocatable_i1p_6d, assign_allocatable_i1p_7d, assign_allocatable_i2p_1d, assign_allocatable_i2p_2d, assign_allocatable_i2p_3d, assign_allocatable_i2p_4d, assign_allocatable_i2p_5d, assign_allocatable_i2p_6d, assign_allocatable_i2p_7d, assign_allocatable_i4p_1d, assign_allocatable_i4p_2d, assign_allocatable_i4p_3d, assign_allocatable_i4p_4d, assign_allocatable_i4p_5d, assign_allocatable_i4p_6d, assign_allocatable_i4p_7d, assign_allocatable_i8p_1d, assign_allocatable_i8p_2d, assign_allocatable_i8p_3d, assign_allocatable_i8p_4d, assign_allocatable_i8p_5d, assign_allocatable_i8p_6d, assign_allocatable_i8p_7d, assign_allocatable_r4p_1d, assign_allocatable_r4p_2d, assign_allocatable_r4p_3d, assign_allocatable_r4p_4d, assign_allocatable_r4p_5d, assign_allocatable_r4p_6d, assign_allocatable_r4p_7d, assign_allocatable_r8p_1d, assign_allocatable_r8p_2d, assign_allocatable_r8p_3d, assign_allocatable_r8p_4d, assign_allocatable_r8p_5d, assign_allocatable_r8p_6d, assign_allocatable_r8p_7d