str_R8P – PENF
str_R8P Function
12 statements
Source File
private elemental function str_R8P(n, no_sign, compact) result(str)
Convert real to string.
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: n
Real to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
logical, intent(in), optional :: compact
Flag for compacting string encoding.
Return Value character(len=DR8P)
Returned string containing input number.
Calls
Called By
Source Code
str_R8P
Source Code
  elemental function str_R8P(n, no_sign, compact) result(str)
  !< Convert real to string.
  real(R8P), intent(in)           :: n       !< Real to be converted.
  logical,   intent(in), optional :: no_sign !< Flag for leaving out the sign.
  logical,   intent(in), optional :: compact !< Flag for *compacting* string encoding.
  character(DR8P)                 :: str     !< Returned string containing input number.
  write(str, FR8P) n                ! Casting of n to string.
  if (n>0._R8P) str(1:1)='+'        ! Prefixing plus if n>0.
  if (present(no_sign)) str=str(2:) ! Leaving out the sign.
  if (present(compact)) then
    if (compact) call compact_real_string(string=str)
  endif
  endfunction str_R8P
All Procedures
bctoi_I1P bctoi_I2P bctoi_I4P bctoi_I8P bcton bctor_R16P bctor_R4P bctor_R8P bit_size bit_size bit_size_chr bit_size_R16P bit_size_R4P bit_size_R8P bstr bstr_I1P bstr_I2P bstr_I4P bstr_I8P bstr_R16P bstr_R4P bstr_R8P byte_size byte_size_chr byte_size_I1P byte_size_I2P byte_size_I4P byte_size_I8P byte_size_R16P byte_size_R4P byte_size_R8P check_endian compact_real_string ctoi_I1P ctoi_I2P ctoi_I4P ctoi_I8P cton ctor_R16P ctor_R4P ctor_R8P digit digit_I1 digit_I2 digit_I4 digit_I8 penf_init penf_print str str_a_I1P str_a_I2P str_a_I4P str_a_I8P str_a_R16P str_a_R4P str_a_R8P str_ascii str_ascii_ascii str_ascii_default str_ascii_ucs4 str_bol str_I1P str_I2P str_I4P str_I8P str_R16P str_R4P str_R8P str_ucs4 str_ucs4_ascii str_ucs4_default str_ucs4_ucs4 strf_I1P strf_I2P strf_I4P strf_I8P strf_R16P strf_R4P strf_R8P strz strz_I1P strz_I2P strz_I4P strz_I8P
Call graph
str_r8p calls compact_real_string
str_a_r8p calls str_r8p
str calls str_r8p, str_a_r8p
penf_test_compact_real calls str
bctor_r4p calls str
bctoi_i1p calls str
bctor_r8p calls str
bctor_r16p calls str
bctoi_i4p calls str
penf_test_all calls str, bcton
bctoi_i8p calls str
bctoi_i2p calls str
bcton calls bctor_r4p, bctoi_i1p, bctor_r8p, bctoi_i4p, bctoi_i8p, bctoi_i2p