str_ascii_default – PENF
str_ascii_default Function
5 statements
Source File
private pure function str_ascii_default(input) result(output)
Convert string of default kind to ASCII string.
 use penf
 character(len=:, kind=ASCII), allocatable :: string
 string = str_ascii('I was DEFAULT kind, but now I am ASCII')
 print "(A)", string
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: input
Input string of default kind.
Return Value character(kind=len=:,ASCII), allocatable
Output string of ASCII kind.
Called By
Source Code
str_ascii_default
Source Code
   pure function str_ascii_default(input) result(output)
   !< Convert string of default kind to ASCII string.
   !<
   !<```fortran
   !< use penf
   !< character(len=:, kind=ASCII), allocatable :: string
   !< string = str_ascii('I was DEFAULT kind, but now I am ASCII')
   !< print "(A)", string
   !<```
   !=> I was DEFAULT kind, but now I am ASCII <<<
   character(len=*), intent(in)              :: input  !< Input string of default kind.
   character(len=:, kind=ASCII), allocatable :: output !< Output string of ASCII kind.
   output = input
   endfunction str_ascii_default
All Procedures
bctoi_I1P bctoi_I2P bctoi_I4P bctoi_I8P bcton bctor_R16P bctor_R4P bctor_R8P bit_size bit_size bit_size_chr bit_size_R16P bit_size_R4P bit_size_R8P bstr bstr_I1P bstr_I2P bstr_I4P bstr_I8P bstr_R16P bstr_R4P bstr_R8P byte_size byte_size_chr byte_size_I1P byte_size_I2P byte_size_I4P byte_size_I8P byte_size_R16P byte_size_R4P byte_size_R8P check_endian compact_real_string ctoi_I1P ctoi_I2P ctoi_I4P ctoi_I8P cton ctor_R16P ctor_R4P ctor_R8P digit digit_I1 digit_I2 digit_I4 digit_I8 penf_init penf_print str str_a_I1P str_a_I2P str_a_I4P str_a_I8P str_a_R16P str_a_R4P str_a_R8P str_ascii str_ascii_ascii str_ascii_default str_ascii_ucs4 str_bol str_I1P str_I2P str_I4P str_I8P str_R16P str_R4P str_R8P str_ucs4 str_ucs4_ascii str_ucs4_default str_ucs4_ucs4 strf_I1P strf_I2P strf_I4P strf_I8P strf_R16P strf_R4P strf_R8P strz strz_I1P strz_I2P strz_I4P strz_I8P
Call graph
str_ascii calls str_ascii_default
volatile_doctest calls str_ascii