str_a_I2P – PENF
str_a_I2P Function
26 statements
Source File
private pure function str_a_I2P(n, no_sign, separator, delimiters) result(str)
Convert integer array to string.
 use penf
 print "(A)", str(n=[1_I2P, -2_I2P])
 use penf
 print "(A)", str(n=[1_I2P, 2_I2P], no_sign=.true.)
 use penf
 print "(A)", str(n=[1_I2P, -2_I2P], separator='|')
 use penf
 print "(A)", str(n=[1_I2P, -2_I2P], delimiters=['(', ')'])
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: n(:)
Integer array to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
character(len=1), intent(in), optional :: separator
Eventual separator of array values.
character(len=*), intent(in), optional :: delimiters(1:2)
Eventual delimiters of array values.
Return Value character(len=:), allocatable
Returned string containing input number.
Calls
Called By
Source Code
str_a_I2P
Source Code
   pure function str_a_I2P(n, no_sign, separator, delimiters) result(str)
   !< Convert integer array to string.
   !<
   !<```fortran
   !< use penf
   !< print "(A)", str(n=[1_I2P, -2_I2P])
   !<```
   !=> +1,-2 <<<
   !<
   !<```fortran
   !< use penf
   !< print "(A)", str(n=[1_I2P, 2_I2P], no_sign=.true.)
   !<```
   !=> 1,2 <<<
   !<
   !<```fortran
   !< use penf
   !< print "(A)", str(n=[1_I2P, -2_I2P], separator='|')
   !<```
   !=> +1|-2 <<<
   !<
   !<```fortran
   !< use penf
   !< print "(A)", str(n=[1_I2P, -2_I2P], delimiters=['(', ')'])
   !<```
   !=> (+1,-2) <<<
   integer(I2P), intent(in)           :: n(:)            !< Integer array to be converted.
   logical,      intent(in), optional :: no_sign         !< Flag for leaving out the sign.
   character(1), intent(in), optional :: separator       !< Eventual separator of array values.
   character(*), intent(in), optional :: delimiters(1:2) !< Eventual delimiters of array values.
   character(len=:), allocatable      :: str             !< Returned string containing input number.
   character(DI2P)                    :: strn            !< String containing of element of input array number.
   character(len=1)                   :: sep             !< Array values separator
   integer                            :: i               !< Counter.
   str = ''
   sep = ','
   if(present(separator)) sep = separator
   if (present(no_sign)) then
     do i=1,size(n)
       strn = str_I2P(no_sign=no_sign, n=n(i))
       str = str//sep//trim(strn)
     enddo
   else
     do i=1,size(n)
       strn = str_I2P(n=n(i))
       str = str//sep//trim(strn)
     enddo
   endif
   str = trim(str(2:))
   if (present(delimiters)) str = delimiters(1)//str//delimiters(2)
   endfunction str_a_I2P
All Procedures
bctoi_I1P bctoi_I2P bctoi_I4P bctoi_I8P bcton bctor_R16P bctor_R4P bctor_R8P bit_size bit_size bit_size_chr bit_size_R16P bit_size_R4P bit_size_R8P bstr bstr_I1P bstr_I2P bstr_I4P bstr_I8P bstr_R16P bstr_R4P bstr_R8P byte_size byte_size_chr byte_size_I1P byte_size_I2P byte_size_I4P byte_size_I8P byte_size_R16P byte_size_R4P byte_size_R8P check_endian compact_real_string ctoi_I1P ctoi_I2P ctoi_I4P ctoi_I8P cton ctor_R16P ctor_R4P ctor_R8P digit digit_I1 digit_I2 digit_I4 digit_I8 penf_init penf_print str str_a_I1P str_a_I2P str_a_I4P str_a_I8P str_a_R16P str_a_R4P str_a_R8P str_ascii str_ascii_ascii str_ascii_default str_ascii_ucs4 str_bol str_I1P str_I2P str_I4P str_I8P str_R16P str_R4P str_R8P str_ucs4 str_ucs4_ascii str_ucs4_default str_ucs4_ucs4 strf_I1P strf_I2P strf_I4P strf_I8P strf_R16P strf_R4P strf_R8P strz strz_I1P strz_I2P strz_I4P strz_I8P
Call graph
str_a_i2p calls str_i2p
str calls str_a_i2p
volatile_doctest calls str, bcton
bctoi_i8p calls str
bctoi_i4p calls str
bctoi_i2p calls str
bctoi_i1p calls str
bcton calls bctoi_i8p, bctoi_i4p, bctoi_i2p, bctoi_i1p