str_a_I1P – PENF
str_a_I1P Function
26 statements
Source File
private pure function str_a_I1P(n, no_sign, separator, delimiters) result(str)
Convert integer array to string.
 use penf
 print "(A)", str(n=[1_I1P, -2_I1P])
 use penf
 print "(A)", str(n=[1_I1P, 2_I1P], no_sign=.true.)
 use penf
 print "(A)", str(n=[1_I1P, -2_I1P], separator='|')
 use penf
 print "(A)", str(n=[1_I1P, -2_I1P], delimiters=['(', ')'])
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: n(:)
Integer array to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
character(len=1), intent(in), optional :: separator
Eventual separator of array values.
character, intent(in), optional :: delimiters(1:2)
Eventual delimiters of array values.
Return Value character(len=:),allocatable
Returned string containing input number.
Calls
Called by
Contents
Source Code
str_a_I1P
Source Code
   pure function str_a_I1P(n, no_sign, separator, delimiters) result(str)
   !< Convert integer array to string.
   !<
   !<```fortran
   !< use penf
   !< print "(A)", str(n=[1_I1P, -2_I1P])
   !<```
   !=> +1,-2 <<<
   !<
   !<```fortran
   !< use penf
   !< print "(A)", str(n=[1_I1P, 2_I1P], no_sign=.true.)
   !<```
   !=> 1,2 <<<
   !<
   !<```fortran
   !< use penf
   !< print "(A)", str(n=[1_I1P, -2_I1P], separator='|')
   !<```
   !=> +1|-2 <<<
   !<
   !<```fortran
   !< use penf
   !< print "(A)", str(n=[1_I1P, -2_I1P], delimiters=['(', ')'])
   !<```
   !=> (+1,-2) <<<
   integer(I1P), intent(in)           :: n(:)            !< Integer array to be converted.
   logical,      intent(in), optional :: no_sign         !< Flag for leaving out the sign.
   character(1), intent(in), optional :: separator       !< Eventual separator of array values.
   character(*), intent(in), optional :: delimiters(1:2) !< Eventual delimiters of array values.
   character(len=:), allocatable      :: str             !< Returned string containing input number.
   character(DI1P)                    :: strn            !< String containing of element of input array number.
   character(len=1)                   :: sep             !< Array values separator
   integer                            :: i               !< Counter.
   str = ''
   sep = ','
   if(present(separator)) sep = separator
   if (present(no_sign)) then
     do i=1,size(n)
       strn = str_I1P(no_sign=no_sign, n=n(i))
       str = str//sep//trim(strn)
     enddo
   else
     do i=1,size(n)
       strn = str_I1P(n=n(i))
       str = str//sep//trim(strn)
     enddo
   endif
   str = trim(str(2:))
   if (present(delimiters)) str = delimiters(1)//str//delimiters(2)
   endfunction str_a_I1P
Call graph
str_a_i1p calls str_i1p
str calls str_a_i1p
volatile_doctest calls str, bcton
bctoi_i8p calls str
bctoi_i2p calls str
bctoi_i4p calls str
bctoi_i1p calls str
bcton calls bctoi_i8p, bctoi_i2p, bctoi_i4p, bctoi_i1p