strz_I4P – PENF
strz_I4P Function
8 statements
Source File
private elemental function strz_I4P(n, nz_pad) result(str)
Convert integer to string, prefixing with the right number of zeros.
 use penf
 print "(A)", strz(n=1_I4P)
 use penf
 print "(A)", strz(n=1_I4P, nz_pad=5)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: n
Integer to be converted.
integer(kind=I4P), intent(in), optional :: nz_pad
Number of zeros padding.
Return Value character(len=DI4P)
Returned string containing input number plus padding zeros.
Called by
Source Code
   elemental function strz_I4P(n, nz_pad) result(str)
   !< Convert integer to string, prefixing with the right number of zeros.
   !<
   !<```fortran
   !< use penf
   !< print "(A)", strz(n=1_I4P)
   !<```
   !=> 0000000001 <<<
   !<
   !<```fortran
   !< use penf
   !< print "(A)", strz(n=1_I4P, nz_pad=5)
   !<```
   !=> 00001 <<<
   integer(I4P), intent(in)           :: n      !< Integer to be converted.
   integer(I4P), intent(in), optional :: nz_pad !< Number of zeros padding.
   character(DI4P)                    :: str    !< Returned string containing input number plus padding zeros.
   write(str,FI4PZP) n                              ! Casting of n to string.
   str=str(2:)                                      ! Leaving out the sign.
   if (present(nz_pad)) str=str(DI4P-nz_pad:DI4P-1) ! Leaving out the extra zeros padding
   endfunction strz_I4P
Call graph
strz calls strz_i4p
volatile_doctest calls strz