assign_allocatable – PENF
assign_allocatable Interface
3 statements
Source File
public interface assign_allocatable
Assign CPU variable with memory checking.
Calls
Called by
Module Procedures
private subroutine assign_allocatable_R8P_1D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind R8P, rank 1). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(inout), allocatable :: lhs(:)
Left hand side of assignement.
real(kind=R8P), intent(in), allocatable :: rhs(:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_R8P_2D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind R8P, rank 2). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(inout), allocatable :: lhs(:,:)
Left hand side of assignement.
real(kind=R8P), intent(in), allocatable :: rhs(:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_R8P_3D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind R8P, rank 3). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(inout), allocatable :: lhs(:,:,:)
Left hand side of assignement.
real(kind=R8P), intent(in), allocatable :: rhs(:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_R8P_4D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind R8P, rank 4). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(inout), allocatable :: lhs(:,:,:,:)
Left hand side of assignement.
real(kind=R8P), intent(in), allocatable :: rhs(:,:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_R8P_5D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind R8P, rank 5). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(inout), allocatable :: lhs(:,:,:,:,:)
Left hand side of assignement.
real(kind=R8P), intent(in), allocatable :: rhs(:,:,:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_R8P_6D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind R8P, rank 6). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(inout), allocatable :: lhs(:,:,:,:,:,:)
Left hand side of assignement.
real(kind=R8P), intent(in), allocatable :: rhs(:,:,:,:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_R8P_7D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind R8P, rank 7). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(inout), allocatable :: lhs(:,:,:,:,:,:,:)
Left hand side of assignement.
real(kind=R8P), intent(in), allocatable :: rhs(:,:,:,:,:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_R4P_1D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind R4P, rank 1). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(inout), allocatable :: lhs(:)
Left hand side of assignement.
real(kind=R4P), intent(in), allocatable :: rhs(:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_R4P_2D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind R4P, rank 2). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(inout), allocatable :: lhs(:,:)
Left hand side of assignement.
real(kind=R4P), intent(in), allocatable :: rhs(:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_R4P_3D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind R4P, rank 3). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(inout), allocatable :: lhs(:,:,:)
Left hand side of assignement.
real(kind=R4P), intent(in), allocatable :: rhs(:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_R4P_4D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind R4P, rank 4). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(inout), allocatable :: lhs(:,:,:,:)
Left hand side of assignement.
real(kind=R4P), intent(in), allocatable :: rhs(:,:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_R4P_5D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind R4P, rank 5). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(inout), allocatable :: lhs(:,:,:,:,:)
Left hand side of assignement.
real(kind=R4P), intent(in), allocatable :: rhs(:,:,:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_R4P_6D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind R4P, rank 6). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(inout), allocatable :: lhs(:,:,:,:,:,:)
Left hand side of assignement.
real(kind=R4P), intent(in), allocatable :: rhs(:,:,:,:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_R4P_7D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind R4P, rank 7). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(inout), allocatable :: lhs(:,:,:,:,:,:,:)
Left hand side of assignement.
real(kind=R4P), intent(in), allocatable :: rhs(:,:,:,:,:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I8P_1D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I8P, rank 1). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(inout), allocatable :: lhs(:)
Left hand side of assignement.
integer(kind=I8P), intent(in), allocatable :: rhs(:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I8P_2D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I8P, rank 2). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(inout), allocatable :: lhs(:,:)
Left hand side of assignement.
integer(kind=I8P), intent(in), allocatable :: rhs(:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I8P_3D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I8P, rank 3). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(inout), allocatable :: lhs(:,:,:)
Left hand side of assignement.
integer(kind=I8P), intent(in), allocatable :: rhs(:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I8P_4D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I8P, rank 4). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(inout), allocatable :: lhs(:,:,:,:)
Left hand side of assignement.
integer(kind=I8P), intent(in), allocatable :: rhs(:,:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I8P_5D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I8P, rank 5). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(inout), allocatable :: lhs(:,:,:,:,:)
Left hand side of assignement.
integer(kind=I8P), intent(in), allocatable :: rhs(:,:,:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I8P_6D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I8P, rank 6). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(inout), allocatable :: lhs(:,:,:,:,:,:)
Left hand side of assignement.
integer(kind=I8P), intent(in), allocatable :: rhs(:,:,:,:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I8P_7D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I8P, rank 7). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(inout), allocatable :: lhs(:,:,:,:,:,:,:)
Left hand side of assignement.
integer(kind=I8P), intent(in), allocatable :: rhs(:,:,:,:,:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I4P_1D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I4P, rank 1). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(inout), allocatable :: lhs(:)
Left hand side of assignement.
integer(kind=I4P), intent(in), allocatable :: rhs(:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I4P_2D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I4P, rank 2). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(inout), allocatable :: lhs(:,:)
Left hand side of assignement.
integer(kind=I4P), intent(in), allocatable :: rhs(:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I4P_3D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I4P, rank 3). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(inout), allocatable :: lhs(:,:,:)
Left hand side of assignement.
integer(kind=I4P), intent(in), allocatable :: rhs(:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I4P_4D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I4P, rank 4). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(inout), allocatable :: lhs(:,:,:,:)
Left hand side of assignement.
integer(kind=I4P), intent(in), allocatable :: rhs(:,:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I4P_5D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I4P, rank 5). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(inout), allocatable :: lhs(:,:,:,:,:)
Left hand side of assignement.
integer(kind=I4P), intent(in), allocatable :: rhs(:,:,:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I4P_6D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I4P, rank 6). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(inout), allocatable :: lhs(:,:,:,:,:,:)
Left hand side of assignement.
integer(kind=I4P), intent(in), allocatable :: rhs(:,:,:,:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I4P_7D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I4P, rank 7). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(inout), allocatable :: lhs(:,:,:,:,:,:,:)
Left hand side of assignement.
integer(kind=I4P), intent(in), allocatable :: rhs(:,:,:,:,:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I2P_1D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I2P, rank 1). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(inout), allocatable :: lhs(:)
Left hand side of assignement.
integer(kind=I2P), intent(in), allocatable :: rhs(:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I2P_2D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I2P, rank 2). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(inout), allocatable :: lhs(:,:)
Left hand side of assignement.
integer(kind=I2P), intent(in), allocatable :: rhs(:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I2P_3D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I2P, rank 3). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(inout), allocatable :: lhs(:,:,:)
Left hand side of assignement.
integer(kind=I2P), intent(in), allocatable :: rhs(:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I2P_4D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I2P, rank 4). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(inout), allocatable :: lhs(:,:,:,:)
Left hand side of assignement.
integer(kind=I2P), intent(in), allocatable :: rhs(:,:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I2P_5D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I2P, rank 5). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(inout), allocatable :: lhs(:,:,:,:,:)
Left hand side of assignement.
integer(kind=I2P), intent(in), allocatable :: rhs(:,:,:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I2P_6D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I2P, rank 6). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(inout), allocatable :: lhs(:,:,:,:,:,:)
Left hand side of assignement.
integer(kind=I2P), intent(in), allocatable :: rhs(:,:,:,:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I2P_7D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I2P, rank 7). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(inout), allocatable :: lhs(:,:,:,:,:,:,:)
Left hand side of assignement.
integer(kind=I2P), intent(in), allocatable :: rhs(:,:,:,:,:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I1P_1D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I1P, rank 1). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(inout), allocatable :: lhs(:)
Left hand side of assignement.
integer(kind=I1P), intent(in), allocatable :: rhs(:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I1P_2D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I1P, rank 2). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(inout), allocatable :: lhs(:,:)
Left hand side of assignement.
integer(kind=I1P), intent(in), allocatable :: rhs(:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I1P_3D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I1P, rank 3). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(inout), allocatable :: lhs(:,:,:)
Left hand side of assignement.
integer(kind=I1P), intent(in), allocatable :: rhs(:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I1P_4D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I1P, rank 4). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(inout), allocatable :: lhs(:,:,:,:)
Left hand side of assignement.
integer(kind=I1P), intent(in), allocatable :: rhs(:,:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I1P_5D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I1P, rank 5). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(inout), allocatable :: lhs(:,:,:,:,:)
Left hand side of assignement.
integer(kind=I1P), intent(in), allocatable :: rhs(:,:,:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I1P_6D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I1P, rank 6). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(inout), allocatable :: lhs(:,:,:,:,:,:)
Left hand side of assignement.
integer(kind=I1P), intent(in), allocatable :: rhs(:,:,:,:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
private subroutine assign_allocatable_I1P_7D(lhs, rhs, file_unit, msg, verbose)
Assign CPU variable with memory checking (kind I1P, rank 7). Variable is returned not allocated if right hand side is not allocated.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(inout), allocatable :: lhs(:,:,:,:,:,:,:)
Left hand side of assignement.
integer(kind=I1P), intent(in), allocatable :: rhs(:,:,:,:,:,:,:)
Right hand side of assignement.
integer(kind=I4P), intent(in), optional :: file_unit
File unit for verbose output.
character(len=*), intent(in), optional :: msg
Message to be printed in verbose mode.
logical, intent(in), optional :: verbose
Flag to activate verbose mode.
Call graph
assign_allocatable calls assign_allocatable_i1p_1d, assign_allocatable_i1p_2d, assign_allocatable_i1p_3d, assign_allocatable_i1p_4d, assign_allocatable_i1p_5d, assign_allocatable_i1p_6d, assign_allocatable_i1p_7d, assign_allocatable_i2p_1d, assign_allocatable_i2p_2d, assign_allocatable_i2p_3d, assign_allocatable_i2p_4d, assign_allocatable_i2p_5d, assign_allocatable_i2p_6d, assign_allocatable_i2p_7d, assign_allocatable_i4p_1d, assign_allocatable_i4p_2d, assign_allocatable_i4p_3d, assign_allocatable_i4p_4d, assign_allocatable_i4p_5d, assign_allocatable_i4p_6d, assign_allocatable_i4p_7d, assign_allocatable_i8p_1d, assign_allocatable_i8p_2d, assign_allocatable_i8p_3d, assign_allocatable_i8p_4d, assign_allocatable_i8p_5d, assign_allocatable_i8p_6d, assign_allocatable_i8p_7d, assign_allocatable_r4p_1d, assign_allocatable_r4p_2d, assign_allocatable_r4p_3d, assign_allocatable_r4p_4d, assign_allocatable_r4p_5d, assign_allocatable_r4p_6d, assign_allocatable_r4p_7d, assign_allocatable_r8p_1d, assign_allocatable_r8p_2d, assign_allocatable_r8p_3d, assign_allocatable_r8p_4d, assign_allocatable_r8p_5d, assign_allocatable_r8p_6d, assign_allocatable_r8p_7d
assign_allocatable_i1p_1d calls allocate_variable
assign_allocatable_i1p_2d calls allocate_variable
assign_allocatable_i1p_3d calls allocate_variable
assign_allocatable_i1p_4d calls allocate_variable
assign_allocatable_i1p_5d calls allocate_variable
assign_allocatable_i1p_6d calls allocate_variable
assign_allocatable_i1p_7d calls allocate_variable
assign_allocatable_i2p_1d calls allocate_variable
assign_allocatable_i2p_2d calls allocate_variable
assign_allocatable_i2p_3d calls allocate_variable
assign_allocatable_i2p_4d calls allocate_variable
assign_allocatable_i2p_5d calls allocate_variable
assign_allocatable_i2p_6d calls allocate_variable
assign_allocatable_i2p_7d calls allocate_variable
assign_allocatable_i4p_1d calls allocate_variable
assign_allocatable_i4p_2d calls allocate_variable
assign_allocatable_i4p_3d calls allocate_variable
assign_allocatable_i4p_4d calls allocate_variable
assign_allocatable_i4p_5d calls allocate_variable
assign_allocatable_i4p_6d calls allocate_variable
assign_allocatable_i4p_7d calls allocate_variable
assign_allocatable_i8p_1d calls allocate_variable
assign_allocatable_i8p_2d calls allocate_variable
assign_allocatable_i8p_3d calls allocate_variable
assign_allocatable_i8p_4d calls allocate_variable
assign_allocatable_i8p_5d calls allocate_variable
assign_allocatable_i8p_6d calls allocate_variable
assign_allocatable_i8p_7d calls allocate_variable
assign_allocatable_r4p_1d calls allocate_variable
assign_allocatable_r4p_2d calls allocate_variable
assign_allocatable_r4p_3d calls allocate_variable
assign_allocatable_r4p_4d calls allocate_variable
assign_allocatable_r4p_5d calls allocate_variable
assign_allocatable_r4p_6d calls allocate_variable
assign_allocatable_r4p_7d calls allocate_variable
assign_allocatable_r8p_1d calls allocate_variable
assign_allocatable_r8p_2d calls allocate_variable
assign_allocatable_r8p_3d calls allocate_variable
assign_allocatable_r8p_4d calls allocate_variable
assign_allocatable_r8p_5d calls allocate_variable
assign_allocatable_r8p_6d calls allocate_variable
assign_allocatable_r8p_7d calls allocate_variable
allocate_variable calls alloc_var_i1p_1d, alloc_var_i1p_2d, alloc_var_i1p_3d, alloc_var_i1p_4d, alloc_var_i1p_5d, alloc_var_i1p_6d, alloc_var_i1p_7d, alloc_var_i2p_1d, alloc_var_i2p_2d, alloc_var_i2p_3d, alloc_var_i2p_4d, alloc_var_i2p_5d, alloc_var_i2p_6d, alloc_var_i2p_7d, alloc_var_i4p_1d, alloc_var_i4p_2d, alloc_var_i4p_3d, alloc_var_i4p_4d, alloc_var_i4p_5d, alloc_var_i4p_6d, alloc_var_i4p_7d, alloc_var_i8p_1d, alloc_var_i8p_2d, alloc_var_i8p_3d, alloc_var_i8p_4d, alloc_var_i8p_5d, alloc_var_i8p_6d, alloc_var_i8p_7d, alloc_var_r4p_1d, alloc_var_r4p_2d, alloc_var_r4p_3d, alloc_var_r4p_4d, alloc_var_r4p_5d, alloc_var_r4p_6d, alloc_var_r4p_7d, alloc_var_r8p_1d, alloc_var_r8p_2d, alloc_var_r8p_3d, alloc_var_r8p_4d, alloc_var_r8p_5d, alloc_var_r8p_6d, alloc_var_r8p_7d
alloc_var_i1p_1d calls str, get_memory_info
alloc_var_i1p_2d calls str, get_memory_info
alloc_var_i1p_3d calls str, get_memory_info
alloc_var_i1p_4d calls str, get_memory_info
alloc_var_i1p_5d calls str, get_memory_info
alloc_var_i1p_6d calls str, get_memory_info
alloc_var_i1p_7d calls str, get_memory_info
alloc_var_i2p_1d calls str, get_memory_info
alloc_var_i2p_2d calls str, get_memory_info
alloc_var_i2p_3d calls str, get_memory_info
alloc_var_i2p_4d calls str, get_memory_info
alloc_var_i2p_5d calls str, get_memory_info
alloc_var_i2p_6d calls str, get_memory_info
alloc_var_i2p_7d calls str, get_memory_info
alloc_var_i4p_1d calls str, get_memory_info
alloc_var_i4p_2d calls str, get_memory_info
alloc_var_i4p_3d calls str, get_memory_info
alloc_var_i4p_4d calls str, get_memory_info
alloc_var_i4p_5d calls str, get_memory_info
alloc_var_i4p_6d calls str, get_memory_info
alloc_var_i4p_7d calls str, get_memory_info
alloc_var_i8p_1d calls str, get_memory_info
alloc_var_i8p_2d calls str, get_memory_info
alloc_var_i8p_3d calls str, get_memory_info
alloc_var_i8p_4d calls str, get_memory_info
alloc_var_i8p_5d calls str, get_memory_info
alloc_var_i8p_6d calls str, get_memory_info
alloc_var_i8p_7d calls str, get_memory_info
alloc_var_r4p_1d calls str, get_memory_info
alloc_var_r4p_2d calls str, get_memory_info
alloc_var_r4p_3d calls str, get_memory_info
alloc_var_r4p_4d calls str, get_memory_info
alloc_var_r4p_5d calls str, get_memory_info
alloc_var_r4p_6d calls str, get_memory_info
alloc_var_r4p_7d calls str, get_memory_info
alloc_var_r8p_1d calls str, get_memory_info
alloc_var_r8p_2d calls str, get_memory_info
alloc_var_r8p_3d calls str, get_memory_info
alloc_var_r8p_4d calls str, get_memory_info
alloc_var_r8p_5d calls str, get_memory_info
alloc_var_r8p_6d calls str, get_memory_info
alloc_var_r8p_7d calls str, get_memory_info
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
get_memory_info calls cton
cton calls ctoi_i1p, ctoi_i2p, ctoi_i4p, ctoi_i8p, ctor_r4p, ctor_r8p
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
volatile_doctest calls assign_allocatable