bstr – PENF
bstr Interface
3 statements
Source File
public interface bstr
Convert number (real and integer) to bit-string (number to bit-string type casting).
Calls
Called by
Contents
Module Procedures
bstr_R8P bstr_R4P bstr_I8P bstr_I4P bstr_I2P bstr_I1P
Module Procedures
private elemental function bstr_R8P(n) result(bstr)
Convert real to string of bits.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: n
Real to be converted.
Return Value character(len=64)
Returned bit-string containing input number.
private elemental function bstr_R4P(n) result(bstr)
Convert real to string of bits.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: n
Real to be converted.
Return Value character(len=32)
Returned bit-string containing input number.
private elemental function bstr_I8P(n) result(bstr)
Convert integer to string of bits.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: n
Real to be converted.
Return Value character(len=64)
Returned bit-string containing input number.
private elemental function bstr_I4P(n) result(bstr)
Convert integer to string of bits.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: n
Real to be converted.
Return Value character(len=32)
Returned bit-string containing input number.
private elemental function bstr_I2P(n) result(bstr)
Convert integer to string of bits.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: n
Real to be converted.
Return Value character(len=16)
Returned bit-string containing input number.
private elemental function bstr_I1P(n) result(bstr)
Convert integer to string of bits.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: n
Real to be converted.
Return Value character(len=8)
Returned bit-string containing input number.
Call graph
bstr calls bstr_r8p, bstr_i2p, bstr_i8p, bstr_i4p, bstr_r4p, bstr_i1p
volatile_doctest calls bstr