byte_size – PENF
byte_size Interface
3 statements
Source File
public interface byte_size
Compute the number of bytes of a variable.
Calls
Called by
Contents
Module Procedures
byte_size_I8P byte_size_I4P byte_size_I2P byte_size_I1P byte_size_R8P byte_size_R4P byte_size_chr
Module Procedures
private elemental function byte_size_I8P(i) result(bytes)
Compute the number of bytes of an integer variable.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: i
Integer variable whose number of bytes must be computed.
Return Value integer(kind=I1P)
Number of bytes of i.
private elemental function byte_size_I4P(i) result(bytes)
Compute the number of bytes of an integer variable.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: i
Integer variable whose number of bytes must be computed.
Return Value integer(kind=I1P)
Number of bytes of i.
private elemental function byte_size_I2P(i) result(bytes)
Compute the number of bytes of an integer variable.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: i
Integer variable whose number of bytes must be computed.
Return Value integer(kind=I1P)
Number of bytes of i.
private elemental function byte_size_I1P(i) result(bytes)
Compute the number of bytes of an integer variable.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: i
Integer variable whose number of bytes must be computed.
Return Value integer(kind=I1P)
Number of bytes of i.
private elemental function byte_size_R8P(i) result(bytes)
Compute the number of bytes of a real variable.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: i
Real variable whose number of bytes must be computed.
Return Value integer(kind=I1P)
Number of bytes of r.
private elemental function byte_size_R4P(i) result(bytes)
Compute the number of bytes of a real variable.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: i
Real variable whose number of bytes must be computed.
Return Value integer(kind=I1P)
Number of bytes of r.
private elemental function byte_size_chr(i) result(bytes)
Compute the number of bytes of a character variable.
Read more…
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: i
Character variable whose number of bytes must be computed.
Return Value integer(kind=I4P)
Number of bytes of c.
Call graph
byte_size calls byte_size_i8p, byte_size_chr, byte_size_r4p, byte_size_i1p, byte_size_i2p, byte_size_r8p, byte_size_i4p
volatile_doctest calls byte_size