cton – PENF
cton Interface
3 statements
Source File
public interface cton
Convert string to number (real and integer, string to number type casting).
Calls
Called by
Contents
Module Procedures
ctor_R8P ctor_R4P ctoi_I8P ctoi_I4P ctoi_I2P ctoi_I1P
Module Procedures
private function ctor_R8P(str, knd, pref, error) result(n)
Convert string to real.
Read more…
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: str
String containing input number.
real(kind=R8P), intent(in) :: knd
Number kind.
character, intent(in), optional :: pref
Prefixing string.
integer(kind=I4P), intent(out), optional :: error
Error trapping flag: 0 no errors, >0 error occurs.
Return Value real(kind=R8P)
Number returned.
private function ctor_R4P(str, knd, pref, error) result(n)
Convert string to real.
Read more…
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: str
String containing input number.
real(kind=R4P), intent(in) :: knd
Number kind.
character, intent(in), optional :: pref
Prefixing string.
integer(kind=I4P), intent(out), optional :: error
Error trapping flag: 0 no errors, >0 error occurs.
Return Value real(kind=R4P)
Number returned.
private function ctoi_I8P(str, knd, pref, error) result(n)
Convert string to integer.
Read more…
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: str
String containing input number.
integer(kind=I8P), intent(in) :: knd
Number kind.
character, intent(in), optional :: pref
Prefixing string.
integer(kind=I4P), intent(out), optional :: error
Error trapping flag: 0 no errors, >0 error occurs.
Return Value integer(kind=I8P)
Number returned.
private function ctoi_I4P(str, knd, pref, error) result(n)
Convert string to integer.
Read more…
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: str
String containing input number.
integer(kind=I4P), intent(in) :: knd
Number kind.
character, intent(in), optional :: pref
Prefixing string.
integer(kind=I4P), intent(out), optional :: error
Error trapping flag: 0 no errors, >0 error occurs.
Return Value integer(kind=I4P)
Number returned.
private function ctoi_I2P(str, knd, pref, error) result(n)
Convert string to integer.
Read more…
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: str
String containing input number.
integer(kind=I2P), intent(in) :: knd
Number kind.
character, intent(in), optional :: pref
Prefixing string.
integer(kind=I4P), intent(out), optional :: error
Error trapping flag: 0 no errors, >0 error occurs.
Return Value integer(kind=I2P)
Number returned.
private function ctoi_I1P(str, knd, pref, error) result(n)
Convert string to integer.
Read more…
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: str
String containing input number.
integer(kind=I1P), intent(in) :: knd
Number kind.
character, intent(in), optional :: pref
Prefixing string.
integer(kind=I4P), intent(out), optional :: error
Error trapping flag: 0 no errors, >0 error occurs.
Return Value integer(kind=I1P)
Number returned.
Call graph
cton calls ctor_r4p, ctoi_i1p, ctoi_i4p, ctor_r8p, ctoi_i8p, ctoi_i2p
volatile_doctest calls cton