str_ascii – PENF
str_ascii Interface
3 statements
Source File
public interface str_ascii
Convert string of any kind to ASCII string.
Calls
Called by
Contents
Module Procedures
str_ascii_default
Module Procedures
private pure function str_ascii_default(input) result(output)
Convert string of default kind to ASCII string.
Read more…
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: input
Input string of default kind.
Return Value character(kind=ASCII,len=:),allocatable
Output string of ASCII kind.
Call graph
str_ascii calls str_ascii_default
volatile_doctest calls str_ascii