strz – PENF
strz Interface
3 statements
Source File
public interface strz
Convert integer, to string, prefixing with the right number of zeros (integer to string type casting with zero padding).
Calls
Called By
Module Procedures
strz_I8P strz_I4P strz_I2P strz_I1P
Module Procedures
private elemental function strz_I8P(n, nz_pad) result(str)
Converting integer to string, prefixing with the right number of zeros.
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: n
Integer to be converted.
integer(kind=I4P), intent(in), optional :: nz_pad
Number of zeros padding.
Return Value character(len=DI8P)
Returned string containing input number plus padding zeros.
private elemental function strz_I4P(n, nz_pad) result(str)
Convert integer to string, prefixing with the right number of zeros.
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: n
Integer to be converted.
integer(kind=I4P), intent(in), optional :: nz_pad
Number of zeros padding.
Return Value character(len=DI4P)
Returned string containing input number plus padding zeros.
private elemental function strz_I2P(n, nz_pad) result(str)
Convert integer to string, prefixing with the right number of zeros.
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: n
Integer to be converted.
integer(kind=I4P), intent(in), optional :: nz_pad
Number of zeros padding.
Return Value character(len=DI2P)
Returned string containing input number plus padding zeros.
private elemental function strz_I1P(n, nz_pad) result(str)
Convert integer to string, prefixing with the right number of zeros.
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: n
Integer to be converted.
integer(kind=I4P), intent(in), optional :: nz_pad
Number of zeros padding.
Return Value character(len=DI1P)
Returned string containing input number plus padding zeros.
All Procedures
bctoi_I1P bctoi_I2P bctoi_I4P bctoi_I8P bcton bctor_R16P bctor_R4P bctor_R8P bit_size bit_size bit_size_chr bit_size_R16P bit_size_R4P bit_size_R8P bstr bstr_I1P bstr_I2P bstr_I4P bstr_I8P bstr_R16P bstr_R4P bstr_R8P byte_size byte_size_chr byte_size_I1P byte_size_I2P byte_size_I4P byte_size_I8P byte_size_R16P byte_size_R4P byte_size_R8P check_endian compact_real_string ctoi_I1P ctoi_I2P ctoi_I4P ctoi_I8P cton ctor_R16P ctor_R4P ctor_R8P digit digit_I1 digit_I2 digit_I4 digit_I8 penf_init penf_print str str_a_I1P str_a_I2P str_a_I4P str_a_I8P str_a_R16P str_a_R4P str_a_R8P str_ascii str_ascii_ascii str_ascii_default str_ascii_ucs4 str_bol str_I1P str_I2P str_I4P str_I8P str_R16P str_R4P str_R8P str_ucs4 str_ucs4_ascii str_ucs4_default str_ucs4_ucs4 strf_I1P strf_I2P strf_I4P strf_I8P strf_R16P strf_R4P strf_R8P strz strz_I1P strz_I2P strz_I4P strz_I8P
Call graph
strz calls strz_i8p, strz_i1p, strz_i2p, strz_i4p
volatile_doctest calls strz