penf_test_all – PENF
penf_test_all Program
24 statements
Source File
Uses:
penf
iso_fortran_env
PENF's testing program.
Usage
 ./penf_test_all
Calls
Source Code
penf_test_all
Source Code
program penf_test_all
!< PENF's testing program.
!<
!<### Usage
!<```bash
!< ./penf_test_all
!<```
use penf
use, intrinsic :: iso_fortran_env, only : stdout=>output_unit
implicit none
call penf_init
call penf_print(unit=stdout)
print "(A)", ''
print "(A)", 'Testing PENF tools'
print "(A)", ASCII_'Casting string_default-to-string_ascii: '//str_ascii('I was DEFAULT kind')
print "(A)", ASCII_'Casting string_ascii-to-string_ascii: '//str_ascii(ASCII_'I was ASCII kind')
print "(A)", ASCII_'Casting string_ucs4-to-string_ascii: '//str_ascii(UCS4_'I was UCS4 kind')
print "(A)", UCS4_'Casting string_default-to-string_ucs4: '//str_ucs4('I was DEFAULT kind')
print "(A)", UCS4_'Casting string_ascii-to-string_ucs4: '//str_ucs4(ASCII_'I was ASCII kind')
print "(A)", UCS4_'Casting string_ucs4-to-string_ucs4: '//str_ucs4(UCS4_'I was UCS4 kind')
print "(A)", 'Casting real-to-string: '//str(n=1._R8P)
print "(A)", 'Casting integer-to-string: '//str(n=11_I8P)
print "(A,"//FR8P//")", 'Casting string-to-real: ', cton(str='2.2d0', knd=1._R8P)
print "(A,"//FI4P//")", 'Casting integer-to-string: ', cton(str='43', knd=1_I4P)
print "(A)", 'Casting integer-to-string with zero padding: '//trim(strz(nz_pad=3, n=34_I8P))
#ifndef __GFORTRAN__
print "(A)", 'Casting real-to-bit_string: '//bstr(n=1._R4P)
#endif
print "(A)", 'Casting integer-to-bit_string: '//bstr(n=1_I4P)
#ifndef __GFORTRAN__
print "(A,"//FR4P//")", 'Casting bit_string-to-real: ', bcton(bstr='00111111100000000000000000000000', knd=1._R4P)
#endif
print "(A,"//FI4P//")", 'Casting bit_string-to-integer: ', bcton(bstr='00000000000000000000000000000001', knd=1_I4P)
print "(A)", 'Number of digit of 1023: '//str(n=digit(1023_I4P))
write(stdout, "(A,L1)") new_line('a')//'Are all tests passed? ', .true.
endprogram penf_test_all
All Programs
penf_test_all penf_test_compact_real
Call graph
penf_test_all calls cton, digit, str_ascii, bstr, penf_print, str, penf_init, bcton, strz, str_ucs4
cton calls ctoi_i2p, ctor_r8p, ctoi_i1p, ctoi_i8p, ctor_r4p, ctoi_i4p
digit calls digit_i2, digit_i1, digit_i8, digit_i4
str_ascii calls str_ascii_default
bstr calls bstr_i1p, bstr_r4p, bstr_i8p, bstr_i4p, bstr_i2p, bstr_r8p
str calls str_i4p, str_a_r4p, str_r4p, strf_i8p, str_i2p, str_r8p, str_a_i1p, strf_r4p, str_a_i4p, strf_i2p, strf_r8p, str_a_i8p, str_a_r8p, strf_i1p, str_i1p, strf_i4p, str_a_i2p, str_i8p, str_bol
penf_init calls check_endian
bcton calls bctor_r4p, bctoi_i1p, bctoi_i4p, bctoi_i8p, bctor_r8p, bctoi_i2p
strz calls strz_i8p, strz_i1p, strz_i2p, strz_i4p
str_ucs4 calls str_ucs4_default
str_a_r4p calls str_r4p
str_r4p calls compact_real_string
str_r8p calls compact_real_string
str_a_i1p calls str_i1p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r8p calls str_r8p
str_a_i2p calls str_i2p
bctor_r4p calls str
bctoi_i1p calls str
bctoi_i4p calls str
bctoi_i8p calls str
bctor_r8p calls str
bctoi_i2p calls str