volatile_doctest – PENF
volatile_doctest Program
5 statements
Source File
Uses:
penf_stringify
penf
Calls
Source Code
volatile_doctest
Source Code
program volatile_doctest
use penf_stringify
 use penf
 print "(A)", strz(n=1_I1P, nz_pad=3)
endprogram volatile_doctest
All Programs
volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest
Call graph
volatile_doctest calls strz
strz calls strz_i8p, strz_i1p, strz_i2p, strz_i4p