volatile_doctest – PENF
volatile_doctest Program
5 statements
Source File
Uses:
penf_stringify
penf
Calls
Source Code
volatile_doctest
Source Code
program volatile_doctest
use penf_stringify
 use penf
 print FI2P, cton(str='-1', knd=1_I2P)
endprogram volatile_doctest
All Programs
volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest
Call graph
volatile_doctest calls cton
cton calls ctoi_i8p, ctoi_i4p, ctoi_i2p, ctoi_i1p, ctor_r4p, ctor_r8p