volatile_doctest – PENF
volatile_doctest Program
5 statements
Source File
Uses:
penf_b_size
penf
Calls
Source Code
volatile_doctest
Source Code
program volatile_doctest
use penf_b_size
 use penf
 print FI1P, byte_size(1._R16P)
endprogram volatile_doctest
All Programs
volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest volatile_doctest
Call graph
volatile_doctest calls byte_size
byte_size calls byte_size_i2p, byte_size_i8p, byte_size_r4p, byte_size_r8p, byte_size_i4p, byte_size_i1p, byte_size_chr