volatile_doctest – PENF
volatile_doctest Program
5 statements
Source File
Uses
penf_stringify
penf
Calls
Contents
Source Code
volatile_doctest
Source Code
program volatile_doctest
use penf_stringify
 use penf
 print FI2P, bcton('0000000000000001', knd=1_I2P)
endprogram volatile_doctest
Call graph
volatile_doctest calls bcton
bcton calls bctor_r8p, bctoi_i1p, bctoi_i8p, bctoi_i4p, bctor_r4p, bctoi_i2p
bctoi_i1p calls str
bctoi_i8p calls str
bctoi_i4p calls str
bctoi_i2p calls str
str calls strf_r8p, str_a_i2p, str_r4p, str_i2p, strf_i8p, str_a_i8p, strf_r4p, str_i8p, str_a_i1p, strf_i1p, str_i1p, str_a_r4p, str_a_i4p, strf_i4p, str_i4p, strf_i2p, str_a_r8p, str_r8p, str_bol
str_a_i2p calls str_i2p
str_r4p calls compact_real_string
str_a_i8p calls str_i8p
str_a_i1p calls str_i1p
str_a_r4p calls str_r4p
str_a_i4p calls str_i4p
str_a_r8p calls str_r8p
str_r8p calls compact_real_string