volatile_doctest – PENF
volatile_doctest Program
5 statements
Source File
Uses
penf_stringify
penf
Calls
Source Code
program volatile_doctest
use penf_stringify
 use penf
 print FR16P, cton(str='-1.0', knd=1._R16P)
endprogram volatile_doctest
Call graph
volatile_doctest calls cton
cton calls ctoi_i1p, ctoi_i2p, ctoi_i4p, ctoi_i8p, ctor_r4p, ctor_r8p