volatile_doctest – PENF
volatile_doctest Program
5 statements
Source File
Uses
penf_stringify
penf
Calls
Source Code
program volatile_doctest
use penf_stringify
 use penf
 print "(A)", str(n=[1_I1P, -2_I1P], delimiters=['(', ')'])
endprogram volatile_doctest
Call graph
volatile_doctest calls str
str calls str_a_i1p, str_a_i2p, str_a_i4p, str_a_i8p, str_a_r4p, str_a_r8p, str_bol, str_i1p, str_i2p, str_i4p, str_i8p, str_r4p, str_r8p, strf_i1p, strf_i2p, strf_i4p, strf_i8p, strf_r4p, strf_r8p
str_a_i1p calls str_i1p
str_a_i2p calls str_i2p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_r8p calls str_r8p
str_r4p calls compact_real_string
str_r8p calls compact_real_string