volatile_doctest – PENF
volatile_doctest Program
5 statements
Source File
Uses
penf_stringify
penf
Calls
Source Code
program volatile_doctest
use penf_stringify
 use penf
 print "(A)", bstr(n=1_I8P)
endprogram volatile_doctest
Call graph
volatile_doctest calls bstr
bstr calls bstr_i1p, bstr_i2p, bstr_i4p, bstr_i8p, bstr_r4p, bstr_r8p